"""initial schema

Revision ID: 13a0256ace3a
Revises:
Create Date: 2026-08-16 18:43:10.189627

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "13a0256ace3a"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)

    op.create_table(
        "movie_feedback",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("imdb_id", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("mood", sa.String(length=512), nullable=True),
        sa.Column("strategy", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "imdb_id", name="uq_user_movie"),
    )
    with op.batch_alter_table("movie_feedback", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_movie_feedback_imdb_id"), ["imdb_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_movie_feedback_user_id"), ["user_id"], unique=False)

    op.create_table(
        "search_history",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("mood", sa.String(length=512), nullable=False),
        sa.Column("strategy", sa.String(length=64), nullable=True),
        sa.Column("results_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("search_history", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_search_history_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_search_history_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("search_history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_search_history_user_id"))
        batch_op.drop_index(batch_op.f("ix_search_history_created_at"))

    op.drop_table("search_history")
    with op.batch_alter_table("movie_feedback", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_movie_feedback_user_id"))
        batch_op.drop_index(batch_op.f("ix_movie_feedback_imdb_id"))

    op.drop_table("movie_feedback")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    # ### end Alembic commands ###
