"""composite index on search_history user_id+created_at

Revision ID: 35a162215ca9
Revises: 13a0256ace3a
Create Date: 2026-08-16 18:43:34.794871

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "35a162215ca9"
down_revision: str | Sequence[str] | None = "13a0256ace3a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("search_history", schema=None) as batch_op:
        batch_op.create_index(
            "ix_search_history_user_created", ["user_id", "created_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("search_history", schema=None) as batch_op:
        batch_op.drop_index("ix_search_history_user_created")

    # ### end Alembic commands ###
