"""watchlist table

Revision ID: 823c5251029c
Revises: 9b1435f8e8a1
Create Date: 2026-08-16 20:09:03.970201

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "823c5251029c"
down_revision: str | Sequence[str] | None = "9b1435f8e8a1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "watchlist",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("imdb_id", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("poster_url", sa.String(length=1024), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "imdb_id", name="uq_watchlist_user_movie"),
    )
    with op.batch_alter_table("watchlist", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_watchlist_imdb_id"), ["imdb_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_watchlist_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("watchlist", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_watchlist_user_id"))
        batch_op.drop_index(batch_op.f("ix_watchlist_imdb_id"))

    op.drop_table("watchlist")
    # ### end Alembic commands ###
